config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    root to: 'devise/sessions#new'
  end
  # devise_for :users, controllers: { confirmations: 'users/confirmations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, Post
      can :create, Comment
      can :create, Like

      can :destroy, Post do |post|
        post.author_id == user.id
      end
      can :destroy, Comment do |comment|
        comment.author_id == user.id
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_counter

  validates :text, presence: true, length: { maximum: 100 }

  def update_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :author_id, presence: true
  validates :post_id, presence: true

  after_save :likes_counter

  def likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def recent_comments
    Comment.order(created_at: :desc).limit(5)
  end

  def update_post_counter
    author.increment!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :asc).limit(3)
  end
end

app/controllers/application_controller.rb
# class ApplicationController < ActionController::Base
#   #   before_action :authenticate_user!

#   protect_from_forgery with: :exception

#   # prevent users to perfrom action without authentication
#   before_action :authenticate_user!

#   before_action :update_allowed_parameters, if: :devise_controller?

#   protected

#   def update_allowed_parameters
#     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
#     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
#   end

#   def after_sign_out_path_for(_resource_or_scope)
#     new_user_session_path
#   end
# end

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_user
  def after_sign_in_path_for(_resource)
    users_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email bio password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.author_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      flash[:notice] = 'Comment was successfully created'
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      render :new, alert: 'Error occurred while creating the comment'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @post.decrement!(:comments_counter)
    @comment.destroy!
    redirect_to user_post_path(id: @post.id), notice: 'Comment was successfully deleted!'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(author_id: current_user.id, post_id: @post)
    if @like.save
      flash[:notice] = 'Like was successfully created'
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      render :new, alert: 'Error Occured While Liking The Post'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(comments: :author)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @author = User.find(params[:user_id])
    @post = @author.posts.new(post_params)

    if @post.save
      redirect_to user_path(id: @post.author_id), notice: 'Post was successfully created'

    else
      render :new, alert: 'Error ccurred while creating the post'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @author = @post.author
    @author.decrement!(:post_counter)
    @post.destroy!
    redirect_to user_posts_path(id: @author.id), notice: 'Post was deleted successfully!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    puts 'anything'
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section>
  <h1>Add comments form</h1>
  <%= form_with model: @comment, url: user_post_comments_path, class: "card left" do |form| %>
    <%= form.label :text %> <br>
    <%= form.text_area :text , cols: 30, rows: 10 %> <br>
    <%= form.submit "Submit", class: "btn" %>
  <% end %>
</section>

app/views/layouts/_navbar.html.erb
<nav>
    <div class="container nav">
      <div class="heading">
        <h2 class="logo"><%= link_to "MyBlogOnRailsApp", users_path %></h2>
      </div>
      <ul class="nav-ul">
        <% if user_signed_in? %>
          <li class="nav-link"><%= link_to "My posts", user_posts_path(current_user.id) %></li>
          <li class="nav-link"><%= link_to "Create a post", new_user_post_path(current_user.id) %></li>
          <li class="nav-link"><%= link_to "Account", edit_user_registration_path, class: "btn right" %></li>
          <li class="nav-link">
            <%= link_to user_path(current_user.id) do %>
              <%= current_user.name %>'s profile
            <% end %>
          </li>
          <li class="nav-link"><%= button_to("Log Out", destroy_user_session_path, method: :delete,class: "nav-link", class: "btn") %></li>
        <% else %>
          <li class="nav-link"><%= link_to "Sign in", new_user_session_path %></li>
          <li class="nav-link"><%= link_to "Sign up", new_user_registration_path %></li>

        <% end %>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

    <body>
    <%= render "layouts/navbar" %>
    <% flash.each do |name, msg| -%>
      <p class="bg-green p-1"><%= msg %></p>
    <% end -%>
    <div class="background-image">
    <div class="container center">
      <%= yield %>
    </div>
    </div>

  </body>
</html>

app/views/likes/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Likes#create</h1>
  <p>Find me in app/views/likes/create.html.erb</p>
</div>

app/views/posts/index.html.erb
<%= render partial: 'shared/signout' %>
<h1>List of all posts for <%= @user.name %></h1>

<section>
  <div class="card flex">
    <div class="user-image border">
      <%= image_tag('R.png',  :width => "100px", :heigth=>"100px") %>
    </div>
    <div class="user-data border">
      <h1><%= @user.name %></h1>
      <p class="number-posts">Number of posts: <%= @user.post_counter %></p>
      <div class="right">
        <%= link_to "See all users", users_path, class: "btn" %>
        <%= link_to "Add a post",new_user_post_path(@user), class: "btn right" %>
      </div>
    </div>
  </div>
</section>
<section>
  <ul>
    <% @posts.each do |post| %>
      <%= link_to user_post_path(user_id: post.author_id, id: post.id) do %>
        <li class="card left">
          <div class="card">
            <h2><%= post.title %></h2>
            <p><%= post.text %></p>
            <div class="right">
              <span>Comments: <%= post.comments_counter %></span>
              <span>Likes: <%= post.likes_counter %> </span>
            </div>
          </div>
          <div class="commets-container">
            <h4>Comments:</h4>
            <ul>
              <% post.comments.each do |comment| %>
                <p><%= comment.author.name %>: <%= comment.text %></p>
              <% end %>
            </ul>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
  <div class="pagination">
  </div>
</section>

app/views/posts/new.html.erb
<section>
  <%= render partial: 'shared/signout' %>
  <h1 class="users-title">Add a new post</h1>
  <%= form_with model: @post, url: user_posts_path, class: "card left" do |form| %>
    <%= form.label :title %> <br>
    <%= form.text_field :title %> <br>
    <%= form.label :text %> <br>
    <%= form.text_area :text , cols: 30, rows: 10 %> <br>
    <%= form.submit "Submit", class: "btn" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<h1>Welcome to post show page</h1>

<section class="card left">
  <%= render partial: 'shared/signout' %>

  <div class="card">
    <h2><%= @post.title %></h2>
    <p><%= @post.text %></p>
    <div class="right">
      <span>Comments: <%= @post.comments_counter %></span>
      <span>Likes: <%= @post.likes_counter %> </span>
    </div>
    <div class="right my-1 flex justify-end">
      <% if user_signed_in? %>
        <%= link_to "Add comment", new_user_post_comment_path(user_id: @post.author_id, post_id: @post.id ), class: "btn" %>
        <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form| %>
          <%= form.submit "Add Like", class: "btn" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="commets-container">
    <h4>Comments:</h4>
    <ul>
          <% @post.comments.includes(:author).includes(:post).each do |comment| %>
        <li class="flex justify-between align-center">
          <p class="p-1"><%= comment.author.name %>: <%= comment.text %></p>
          <% if can? :destroy, comment %>
            <%= button_to "Delete comment", user_post_comment_path(user_id: comment.author.id, post_id: comment.post.id, id: comment.id), method: :delete, class: 'btn-del'  %>
          <% end %>
        </li>
        <% end %>
</section>

app/views/shared/_signout.html.erb
<% if user_signed_in? %>
        <%= form_tag(destroy_user_session_path, method: :delete, class: "d-flex justify-content-center") do %>
          <%= submit_tag("Sign Out", class: "btn btn-danger") %>
        <% end %>
    <% end %>

app/views/users/index.html.erb
<section class="background">
  <%= render partial: 'shared/signout' %>
    <h1 class="users-title">Welcome to Users page</h1>
    <ul>
      <% @users.each do |user|%>
        <%= link_to user do %>
          <li class="card flex hover">
            <div class="user-image border">
              <%= image_tag('R.png',  :width => "100px", :heigth=>"100px") %>
            </div>
            <div class="user-data border">
              <h1><%= user.name %></h1>
              <p class="number-posts">Number of posts: <%= user.post_counter %></p>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>  
</section>

app/views/users/show.html.erb
<section>
  <%= render partial: 'shared/signout' %>
  <div class="card flex">
    <div class="user-image border">
      <%= image_tag('R.png',  :width => "100px", :heigth=>"100px") %>
    </div>
    <div class="user-data border">
      <h1><%= @user.name %></h1>
      <p class="number-posts">Number of posts: <%= @user.post_counter %></p>
    </div>
  </div>
  <div class="card left">
    <h4>Biography:</h4><br>
    <p><%= @user.bio %></p>
  </div>
</section>
<section>
  <h1 class="users-title">List of recent Posts</h1>
  <ul>
    <% @user.recent_posts.each do |post| %>
      <%= link_to user_post_path(user_id: post.author_id, id: post.id) do %>
        <li class="card left">
          <h2><%= post.title%></h2>
          <p><%= post.text%></p>
          <div class="right">
            <span>Comments: <%= post.comments_counter %></span>
            <span>Likes: <%= post.likes_counter %> </span>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
  <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "btn" %>
</section>